#!/bin/bash
mvn clean package assembly:single
#java -jar FlexChain_Processor.jar
java --module-path /home/matt/OpenJFX/javafx-sdk-17.0.0.1/lib --add-modules=javafx.controls,javafx.fxml -jar target/Translator-1.0-SNAPSHOT-jar-with-dependencies.jar
