#!/bin/bash
mvn clean package assembly:single
#java -jar FlexChain_Processor.jar
export PATH_TO_FX=~/OpenJFX/javafx-sdk-17.0.0.1/lib
java --module-path $PATH_TO_FX --add-modules=javafx.controls,javafx.fxml -jar target/Translator-1.0-SNAPSHOT-jar-with-dependencies.jar
